apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260617-210212-dn09ykd2v0sf-service
spec:
  selector:
    app: enterprise-system-20260617-210212-dn09ykd2v0sf
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
